apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: app-pdb
  namespace: app
  labels:
    app: app-http
    version: v0.22.0
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: app-http
