apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hive-pdb
  namespace: app
  labels:
    app: hive
    version: v0.22.0
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: hive
