apiVersion: v1
kind: ServiceAccount
metadata:
  name: hive
  namespace: app
  labels:
    app: hive
    version: v0.31.0
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: app
  name: hive-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hive-role-binding
  namespace: app
subjects:
  - kind: ServiceAccount
    name: hive
    namespace: app
roleRef:
  kind: Role
  name: hive-role
  apiGroup: rbac.authorization.k8s.io
