apiVersion: v1
kind: Service
metadata:
  name: hive-external
  namespace: app
  labels:
    app: hive
    version: v0.31.0
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "hive-lb"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/ping"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "9999"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 9999
      targetPort: http
      protocol: TCP
  selector:
    app: hive
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: hive
  namespace: app
  labels:
    app: hive
    version: v0.31.0
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9999
      targetPort: http
      protocol: TCP
  selector:
    app: hive
