package model

import "time"

// CapturedSession is a recorded agent session shipped to hive-server.
// Inspired by entire.io's checkpoint format but designed for OpenClaw/ACP.
type CapturedSession struct {
	// Hive-assigned ID (UUID).
	ID string `json:"id,omitempty"`

	// Agent identity.
	AgentID    string `json:"agent_id"`
	SessionKey string `json:"session_key,omitempty"`
	SessionID  string `json:"session_id,omitempty"`
	Channel    string `json:"channel,omitempty"`
	SenderID   string `json:"sender_id,omitempty"`

	// Model and provider used during the session.
	Model    string `json:"model,omitempty"`
	Provider string `json:"provider,omitempty"`

	// Timing (optional — zero values are valid for incomplete sessions).
	StartedAt  *time.Time `json:"started_at,omitempty"`
	FinishedAt *time.Time `json:"finished_at,omitempty"`

	// Token usage aggregated across all turns (optional).
	Usage *CapturedUsage `json:"usage,omitempty"`

	// Workspace context.
	Repo  string   `json:"repo,omitempty"`
	Paths []string `json:"paths,omitempty"` // files modified or touched

	// Summary (human-readable, generated by the agent or harness).
	Summary string `json:"summary,omitempty"`

	// Full transcript: ordered list of turns.
	Turns []CapturedTurn `json:"turns,omitempty"`

	// Tool calls made across all turns (denormalized for easy querying).
	ToolCalls []CapturedToolCall `json:"tool_calls,omitempty"`

	// Metadata: arbitrary key-value pairs.
	Metadata map[string]any `json:"metadata,omitempty"`

	// Parent session ID (for nested sub-agent sessions).
	ParentSessionID string `json:"parent_session_id,omitempty"`

	// Hive-assigned timestamps.
	CreatedAt time.Time `json:"created_at,omitempty"`
}

// CapturedUsage holds aggregated token counts for a session.
// All fields are optional (zero values are valid — not all sessions track usage).
type CapturedUsage struct {
	InputTokens      int     `json:"input_tokens,omitempty"`
	OutputTokens     int     `json:"output_tokens,omitempty"`
	CacheReadTokens  int     `json:"cache_read_tokens,omitempty"`
	CacheWriteTokens int     `json:"cache_write_tokens,omitempty"`
	TotalTokens      int     `json:"total_tokens,omitempty"`
	EstimatedCostUSD float64 `json:"estimated_cost_usd,omitempty"`
}

// CapturedTurn is a single prompt+response turn in a session.
type CapturedTurn struct {
	Role      string         `json:"role"` // "user" | "assistant"
	Content   string         `json:"content"`
	Timestamp *time.Time     `json:"timestamp,omitempty"`
	Usage     *CapturedUsage `json:"usage,omitempty"` // per-turn usage (assistant only)
	Model     string         `json:"model,omitempty"`
}

// CapturedToolCall records a single tool invocation during a session.
type CapturedToolCall struct {
	Tool      string     `json:"tool"`
	Input     string     `json:"input,omitempty"`  // JSON-encoded input
	Output    string     `json:"output,omitempty"` // truncated output
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// SessionFilter controls which sessions are returned by ListSessions.
type SessionFilter struct {
	AgentID string
	Repo    string
	Path    string // partial match against paths array
	Since   time.Time
	Limit   int
}
